[project]
name = "cursorweb2api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "curl-cffi>=0.13.0",
    "fastapi>=0.117.1",
    "loguru>=0.7.3",
    "sse-starlette>=3.0.2",
    "uvicorn>=0.37.0",
]
